/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as InformacoesRouteImport } from './routes/informacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificarCodigoRouteImport } from './routes/verificar.$codigo'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinicursosRouteImport } from './routes/_authenticated/minicursos'
import { Route as AuthenticatedInscricaoRouteImport } from './routes/_authenticated/inscricao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminVerificarRouteImport } from './routes/_authenticated/admin/verificar'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminProgramacaoRouteImport } from './routes/_authenticated/admin/programacao'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminMinicursosRouteImport } from './routes/_authenticated/admin/minicursos'
import { Route as AuthenticatedAdminInscricoesRouteImport } from './routes/_authenticated/admin/inscricoes'
import { Route as AuthenticatedAdminCertificadosRouteImport } from './routes/_authenticated/admin/certificados'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacoesRoute = InformacoesRouteImport.update({
  id: '/informacoes',
  path: '/informacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarCodigoRoute = VerificarCodigoRouteImport.update({
  id: '/$codigo',
  path: '/$codigo',
  getParentRoute: () => VerificarRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinicursosRoute = AuthenticatedMinicursosRouteImport.update({
  id: '/minicursos',
  path: '/minicursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInscricaoRoute = AuthenticatedInscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVerificarRoute =
  AuthenticatedAdminVerificarRouteImport.update({
    id: '/verificar',
    path: '/verificar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProgramacaoRoute =
  AuthenticatedAdminProgramacaoRouteImport.update({
    id: '/programacao',
    path: '/programacao',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMinicursosRoute =
  AuthenticatedAdminMinicursosRouteImport.update({
    id: '/minicursos',
    path: '/minicursos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInscricoesRoute =
  AuthenticatedAdminInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCertificadosRoute =
  AuthenticatedAdminCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informacoes': typeof InformacoesRoute
  '/programacao': typeof ProgramacaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verificar': typeof VerificarRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inscricao': typeof AuthenticatedInscricaoRoute
  '/minicursos': typeof AuthenticatedMinicursosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/inscricoes': typeof AuthenticatedAdminInscricoesRoute
  '/admin/minicursos': typeof AuthenticatedAdminMinicursosRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/programacao': typeof AuthenticatedAdminProgramacaoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/verificar': typeof AuthenticatedAdminVerificarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/informacoes': typeof InformacoesRoute
  '/programacao': typeof ProgramacaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verificar': typeof VerificarRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inscricao': typeof AuthenticatedInscricaoRoute
  '/minicursos': typeof AuthenticatedMinicursosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/inscricoes': typeof AuthenticatedAdminInscricoesRoute
  '/admin/minicursos': typeof AuthenticatedAdminMinicursosRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/programacao': typeof AuthenticatedAdminProgramacaoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/verificar': typeof AuthenticatedAdminVerificarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/informacoes': typeof InformacoesRoute
  '/programacao': typeof ProgramacaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verificar': typeof VerificarRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inscricao': typeof AuthenticatedInscricaoRoute
  '/_authenticated/minicursos': typeof AuthenticatedMinicursosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/_authenticated/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/_authenticated/admin/inscricoes': typeof AuthenticatedAdminInscricoesRoute
  '/_authenticated/admin/minicursos': typeof AuthenticatedAdminMinicursosRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/programacao': typeof AuthenticatedAdminProgramacaoRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/verificar': typeof AuthenticatedAdminVerificarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/informacoes'
    | '/programacao'
    | '/reset-password'
    | '/verificar'
    | '/admin'
    | '/certificados'
    | '/dashboard'
    | '/inscricao'
    | '/minicursos'
    | '/perfil'
    | '/verificar/$codigo'
    | '/admin/certificados'
    | '/admin/inscricoes'
    | '/admin/minicursos'
    | '/admin/notificacoes'
    | '/admin/programacao'
    | '/admin/usuarios'
    | '/admin/verificar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/informacoes'
    | '/programacao'
    | '/reset-password'
    | '/verificar'
    | '/certificados'
    | '/dashboard'
    | '/inscricao'
    | '/minicursos'
    | '/perfil'
    | '/verificar/$codigo'
    | '/admin/certificados'
    | '/admin/inscricoes'
    | '/admin/minicursos'
    | '/admin/notificacoes'
    | '/admin/programacao'
    | '/admin/usuarios'
    | '/admin/verificar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/informacoes'
    | '/programacao'
    | '/reset-password'
    | '/verificar'
    | '/_authenticated/admin'
    | '/_authenticated/certificados'
    | '/_authenticated/dashboard'
    | '/_authenticated/inscricao'
    | '/_authenticated/minicursos'
    | '/_authenticated/perfil'
    | '/verificar/$codigo'
    | '/_authenticated/admin/certificados'
    | '/_authenticated/admin/inscricoes'
    | '/_authenticated/admin/minicursos'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/programacao'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/verificar'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InformacoesRoute: typeof InformacoesRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerificarRoute: typeof VerificarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacoes': {
      id: '/informacoes'
      path: '/informacoes'
      fullPath: '/informacoes'
      preLoaderRoute: typeof InformacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar/$codigo': {
      id: '/verificar/$codigo'
      path: '/$codigo'
      fullPath: '/verificar/$codigo'
      preLoaderRoute: typeof VerificarCodigoRouteImport
      parentRoute: typeof VerificarRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minicursos': {
      id: '/_authenticated/minicursos'
      path: '/minicursos'
      fullPath: '/minicursos'
      preLoaderRoute: typeof AuthenticatedMinicursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inscricao': {
      id: '/_authenticated/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof AuthenticatedInscricaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/verificar': {
      id: '/_authenticated/admin/verificar'
      path: '/verificar'
      fullPath: '/admin/verificar'
      preLoaderRoute: typeof AuthenticatedAdminVerificarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programacao': {
      id: '/_authenticated/admin/programacao'
      path: '/programacao'
      fullPath: '/admin/programacao'
      preLoaderRoute: typeof AuthenticatedAdminProgramacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/minicursos': {
      id: '/_authenticated/admin/minicursos'
      path: '/minicursos'
      fullPath: '/admin/minicursos'
      preLoaderRoute: typeof AuthenticatedAdminMinicursosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inscricoes': {
      id: '/_authenticated/admin/inscricoes'
      path: '/inscricoes'
      fullPath: '/admin/inscricoes'
      preLoaderRoute: typeof AuthenticatedAdminInscricoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/certificados': {
      id: '/_authenticated/admin/certificados'
      path: '/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AuthenticatedAdminCertificadosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCertificadosRoute: typeof AuthenticatedAdminCertificadosRoute
  AuthenticatedAdminInscricoesRoute: typeof AuthenticatedAdminInscricoesRoute
  AuthenticatedAdminMinicursosRoute: typeof AuthenticatedAdminMinicursosRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminProgramacaoRoute: typeof AuthenticatedAdminProgramacaoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVerificarRoute: typeof AuthenticatedAdminVerificarRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCertificadosRoute: AuthenticatedAdminCertificadosRoute,
    AuthenticatedAdminInscricoesRoute: AuthenticatedAdminInscricoesRoute,
    AuthenticatedAdminMinicursosRoute: AuthenticatedAdminMinicursosRoute,
    AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
    AuthenticatedAdminProgramacaoRoute: AuthenticatedAdminProgramacaoRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminVerificarRoute: AuthenticatedAdminVerificarRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInscricaoRoute: typeof AuthenticatedInscricaoRoute
  AuthenticatedMinicursosRoute: typeof AuthenticatedMinicursosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInscricaoRoute: AuthenticatedInscricaoRoute,
  AuthenticatedMinicursosRoute: AuthenticatedMinicursosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface VerificarRouteChildren {
  VerificarCodigoRoute: typeof VerificarCodigoRoute
}

const VerificarRouteChildren: VerificarRouteChildren = {
  VerificarCodigoRoute: VerificarCodigoRoute,
}

const VerificarRouteWithChildren = VerificarRoute._addFileChildren(
  VerificarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InformacoesRoute: InformacoesRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerificarRoute: VerificarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
